spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: bank
    password: 'bankpass'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
fixer:
  dev:
    access_key: ???
    url: http://data.fixer.io/api/latest
jwt:
  dev:
    secret: isthisthereallife